/*
 * ODS_ProxyView.java
 */

package ods_proxy;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;

import javax.swing.text.*;

/**
 * The application's main frame.
 */
public class ODS_ProxyView extends FrameView {

    public ODS_ProxyView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });

        jFormattedTextField_COM_port.setText("COM1");
        jFormattedTextField_BaudRate.setText("115200");
        jTextField_ConsoleServerPort.setText("23");
        jFormattedTextField_Shell_IP.setText("127.0.0.1");
        jFormattedTextField_Shell_Port.setText("23");
        jTextField_ShellServerPort.setText("1234");
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ODS_ProxyApp.getApplication().getMainFrame();
            aboutBox = new ODS_ProxyAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ODS_ProxyApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Console = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Shell = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField_COM_port = new javax.swing.JFormattedTextField();
        jFormattedTextField_BaudRate = new javax.swing.JFormattedTextField();
        jFormattedTextField_Shell_IP = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField_Shell_Port = new javax.swing.JFormattedTextField();
        jButton_Console_Connect = new javax.swing.JButton();
        jButton_Shell_Connect = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_ConsoleServerPort = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_ShellServerPort = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        jMenuItem_ShowClient = new javax.swing.JMenuItem();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea_Console.setColumns(20);
        jTextArea_Console.setEditable(false);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(ods_proxy.ODS_ProxyApp.class).getContext().getResourceMap(ODS_ProxyView.class);
        jTextArea_Console.setFont(resourceMap.getFont("jTextArea_Console.font")); // NOI18N
        jTextArea_Console.setRows(5);
        jTextArea_Console.setName("jTextArea_Console"); // NOI18N
        jTextArea_Console.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_ConsoleKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Console);

        jSplitPane1.setTopComponent(jScrollPane1);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea_Shell.setColumns(20);
        jTextArea_Shell.setEditable(false);
        jTextArea_Shell.setFont(resourceMap.getFont("jTextArea_Shell.font")); // NOI18N
        jTextArea_Shell.setRows(5);
        jTextArea_Shell.setName("jTextArea_Shell"); // NOI18N
        jTextArea_Shell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_ShellKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea_Shell);

        jSplitPane1.setRightComponent(jScrollPane2);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jFormattedTextField_COM_port.setText(resourceMap.getString("jFormattedTextField_COM_port.text")); // NOI18N
        jFormattedTextField_COM_port.setName("jFormattedTextField_COM_port"); // NOI18N

        jFormattedTextField_BaudRate.setText(resourceMap.getString("jFormattedTextField_BaudRate.text")); // NOI18N
        jFormattedTextField_BaudRate.setName("jFormattedTextField_BaudRate"); // NOI18N

        jFormattedTextField_Shell_IP.setText(resourceMap.getString("jFormattedTextField_Shell_IP.text")); // NOI18N
        jFormattedTextField_Shell_IP.setName("jFormattedTextField_Shell_IP"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jFormattedTextField_Shell_Port.setText(resourceMap.getString("jFormattedTextField_Shell_Port.text")); // NOI18N
        jFormattedTextField_Shell_Port.setName("jFormattedTextField_Shell_Port"); // NOI18N

        jButton_Console_Connect.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton_Console_Connect.setName("jButton1"); // NOI18N
        jButton_Console_Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Console_ConnectMouseClicked(evt);
            }
        });

        jButton_Shell_Connect.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton_Shell_Connect.setName("jButton2"); // NOI18N
        jButton_Shell_Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Shell_ConnectMouseClicked(evt);
            }
        });

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jTextField_ConsoleServerPort.setText(resourceMap.getString("jTextField_ConsoleServerPort.text")); // NOI18N
        jTextField_ConsoleServerPort.setName("jTextField_ConsoleServerPort"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTextField_ShellServerPort.setText(resourceMap.getString("jTextField_ShellServerPort.text")); // NOI18N
        jTextField_ShellServerPort.setName("jTextField_ShellServerPort"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_COM_port, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ConsoleServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_Console_Connect)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_Shell_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_Shell_Port, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_ShellServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton_Shell_Connect)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_COM_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jFormattedTextField_BaudRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Console_Connect)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_ConsoleServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField_Shell_Port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_Shell_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Shell_Connect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_ShellServerPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(ods_proxy.ODS_ProxyApp.class).getContext().getActionMap(ODS_ProxyView.class, this);
        jMenuItem_ShowClient.setAction(actionMap.get("ShowClient")); // NOI18N
        jMenuItem_ShowClient.setText(resourceMap.getString("jMenuItem_ShowClient.text")); // NOI18N
        jMenuItem_ShowClient.setName("jMenuItem_ShowClient"); // NOI18N
        fileMenu.add(jMenuItem_ShowClient);

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 409, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Console_ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Console_ConnectMouseClicked
        // TODO add your handling code here:
        consoleHandler.ConnectButtonClicked(
            jFormattedTextField_COM_port.getText(),
            jFormattedTextField_BaudRate.getText(),
            jTextField_ConsoleServerPort.getText()
        );
    }//GEN-LAST:event_jButton_Console_ConnectMouseClicked

    private void jButton_Shell_ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Shell_ConnectMouseClicked
        // TODO add your handling code here:
        shellHandler.ConnectButtonClicked(
            jFormattedTextField_Shell_IP.getText(),
            jFormattedTextField_Shell_Port.getText(),
            jTextField_ShellServerPort.getText()
        );
    }//GEN-LAST:event_jButton_Shell_ConnectMouseClicked

    private void jTextArea_ConsoleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_ConsoleKeyTyped
        // TODO add your handling code here:
        consoleHandler.KeyTyped( evt.getKeyChar() );
    }//GEN-LAST:event_jTextArea_ConsoleKeyTyped

    private void jTextArea_ShellKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_ShellKeyTyped
        // TODO add your handling code here:
        shellHandler.KeyTyped( evt.getKeyChar() );
    }//GEN-LAST:event_jTextArea_ShellKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Console_Connect;
    private javax.swing.JButton jButton_Shell_Connect;
    private javax.swing.JFormattedTextField jFormattedTextField_BaudRate;
    private javax.swing.JFormattedTextField jFormattedTextField_COM_port;
    private javax.swing.JFormattedTextField jFormattedTextField_Shell_IP;
    private javax.swing.JFormattedTextField jFormattedTextField_Shell_Port;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem_ShowClient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea_Console;
    private javax.swing.JTextArea jTextArea_Shell;
    private javax.swing.JTextField jTextField_ConsoleServerPort;
    private javax.swing.JTextField jTextField_ShellServerPort;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;

    private ShowClientDialog  showClientBox;

    //------------------------------------------------------------------------

    public void SetConsoleConnectButtonText( String text ) {
        jButton_Console_Connect.setText( text );
        jTextArea_Console.grabFocus();
    }

    public void SetShellConnectButtonText( String text ) {
        jButton_Shell_Connect.setText( text );
        jTextArea_Shell.grabFocus();
    }

    public void WriteToConsoleWindow( String msg ) {
        writeToTextArea( jTextArea_Console, msg );
    }

    public void WriteToShellWindow( String msg ) {
        writeToTextArea( jTextArea_Shell, msg );
    }

    private void writeToTextArea( javax.swing.JTextArea textArea, String msg ) {
        if (msg.charAt(0) == '\007') return; // beep
        if (msg.charAt(0) != '\b')
        {
            textArea.append(msg);
            textArea.setCaretPosition(textArea.getDocument().getLength()-1);
        }
        else if (textArea.getDocument().getLength() > 0)
        {
            try {
                textArea.getDocument().remove( textArea.getDocument().getLength()-1, 1 );
            } catch (BadLocationException e) { e.printStackTrace(); }
            textArea.setCaretPosition(textArea.getDocument().getLength()-1);
        }
    }

    private ConsoleWindowInterface  consoleHandler;
    private ShellWindowInterface  shellHandler;

    public void setConsoleHandler( ConsoleWindowInterface handler ) {
        consoleHandler = handler;
    }

    public void setShellHandler( ShellWindowInterface handler ) {
        shellHandler = handler;
    }

    @Action
    public void ShowClient() {
        if (showClientBox == null) {
            JFrame mainFrame = ODS_ProxyApp.getApplication().getMainFrame();
            showClientBox = new ShowClientDialog( mainFrame, true );
            showClientBox.setLocationRelativeTo(mainFrame);
        }

        showClientBox.SetText( ODS_ProxyApp.getApplication().GetClients() );

        ODS_ProxyApp.getApplication().show(showClientBox);
    }
}
